//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScavengerHunt.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScavengerHunt.Web.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achievement.
        /// </summary>
        public static string Achievement {
            get {
                return ResourceManager.GetString("Achievement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which side of the force will you join???.
        /// </summary>
        public static string AreYouReady {
            get {
                return ResourceManager.GetString("AreYouReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asign.
        /// </summary>
        public static string Asign {
            get {
                return ResourceManager.GetString("Asign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus Points.
        /// </summary>
        public static string BonusPoints {
            get {
                return ResourceManager.GetString("BonusPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to capped.
        /// </summary>
        public static string capped {
            get {
                return ResourceManager.GetString("capped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password Form.
        /// </summary>
        public static string ChangePasswordForm {
            get {
                return ResourceManager.GetString("ChangePasswordForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapsible.
        /// </summary>
        public static string Collapsible {
            get {
                return ResourceManager.GetString("Collapsible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of validations.
        /// </summary>
        public static string CompletedNumber {
            get {
                return ResourceManager.GetString("CompletedNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact user.
        /// </summary>
        public static string ContactUser {
            get {
                return ResourceManager.GetString("ContactUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new.
        /// </summary>
        public static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create or Join a team!.
        /// </summary>
        public static string CreateOrJoinTeam {
            get {
                return ResourceManager.GetString("CreateOrJoinTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Rankings.
        /// </summary>
        public static string CurrentRankings {
            get {
                return ResourceManager.GetString("CurrentRankings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataManagement.
        /// </summary>
        public static string DataManagement {
            get {
                return ResourceManager.GetString("DataManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this?.
        /// </summary>
        public static string DeleteValidation {
            get {
                return ResourceManager.GetString("DeleteValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        public static string Documentation {
            get {
                return ResourceManager.GetString("Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expecting.
        /// </summary>
        public static string Expecting {
            get {
                return ResourceManager.GetString("Expecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The judges are expecting a.
        /// </summary>
        public static string ExpectingType {
            get {
                return ResourceManager.GetString("ExpectingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag submissions.
        /// </summary>
        public static string FlagSubmissions {
            get {
                return ResourceManager.GetString("FlagSubmissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for.
        /// </summary>
        public static string For {
            get {
                return ResourceManager.GetString("For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has slideshow.
        /// </summary>
        public static string HasSlideshow {
            get {
                return ResourceManager.GetString("HasSlideshow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serious Scavenger Hunt is a free, open source web applicaiton for building, running and managing great scavenger hunts..
        /// </summary>
        public static string HomeJumbotronLead {
            get {
                return ResourceManager.GetString("HomeJumbotronLead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home page.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join.
        /// </summary>
        public static string Join {
            get {
                return ResourceManager.GetString("Join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join an existing team.
        /// </summary>
        public static string JoinExistingTeam {
            get {
                return ResourceManager.GetString("JoinExistingTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must choose a side before doing puzzles..
        /// </summary>
        public static string JoinExistingTeamExplanation {
            get {
                return ResourceManager.GetString("JoinExistingTeamExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Judged.
        /// </summary>
        public static string Judged {
            get {
                return ResourceManager.GetString("Judged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Judge Feedback.
        /// </summary>
        public static string JudgeFeedback {
            get {
                return ResourceManager.GetString("JudgeFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Judgement.
        /// </summary>
        public static string Judgement {
            get {
                return ResourceManager.GetString("Judgement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Judge Notes.
        /// </summary>
        public static string JudgeNotes {
            get {
                return ResourceManager.GetString("JudgeNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword.
        /// </summary>
        public static string Keyword {
            get {
                return ResourceManager.GetString("Keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leader?.
        /// </summary>
        public static string Leader {
            get {
                return ResourceManager.GetString("Leader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long description.
        /// </summary>
        public static string LongDescription {
            get {
                return ResourceManager.GetString("LongDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage team.
        /// </summary>
        public static string ManageTeam {
            get {
                return ResourceManager.GetString("ManageTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Users.
        /// </summary>
        public static string ManageUsers {
            get {
                return ResourceManager.GetString("ManageUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Score.
        /// </summary>
        public static string MaximumScore {
            get {
                return ResourceManager.GetString("MaximumScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members.
        /// </summary>
        public static string Members {
            get {
                return ResourceManager.GetString("Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of ranks.
        /// </summary>
        public static string NumberOfRanks {
            get {
                return ResourceManager.GetString("NumberOfRanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} characters long..
        /// </summary>
        public static string PasswordLengthError {
            get {
                return ResourceManager.GetString("PasswordLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password and confirmation password do not match..
        /// </summary>
        public static string PasswordMismatchError {
            get {
                return ResourceManager.GetString("PasswordMismatchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to points!.
        /// </summary>
        public static string Points {
            get {
                return ResourceManager.GetString("Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published.
        /// </summary>
        public static string Published {
            get {
                return ResourceManager.GetString("Published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank.
        /// </summary>
        public static string Rank {
            get {
                return ResourceManager.GetString("Rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranks.
        /// </summary>
        public static string Ranks {
            get {
                return ResourceManager.GetString("Ranks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May we recommend.
        /// </summary>
        public static string Recommend {
            get {
                return ResourceManager.GetString("Recommend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles for user.
        /// </summary>
        public static string RolesForUser {
            get {
                return ResourceManager.GetString("RolesForUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scavenger Hunt.
        /// </summary>
        public static string ScavengerHunt {
            get {
                return ResourceManager.GetString("ScavengerHunt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        public static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scoreboard.
        /// </summary>
        public static string Scoreboard {
            get {
                return ResourceManager.GetString("Scoreboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score to obtain rank.
        /// </summary>
        public static string ScoreToAchieve {
            get {
                return ResourceManager.GetString("ScoreToAchieve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret.
        /// </summary>
        public static string Secret {
            get {
                return ResourceManager.GetString("Secret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short description.
        /// </summary>
        public static string ShortDescription {
            get {
                return ResourceManager.GetString("ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slideshow.
        /// </summary>
        public static string Slideshow {
            get {
                return ResourceManager.GetString("Slideshow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source code.
        /// </summary>
        public static string SourceCode {
            get {
                return ResourceManager.GetString("SourceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start your journey!.
        /// </summary>
        public static string StartJourney {
            get {
                return ResourceManager.GetString("StartJourney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already part of a team and are ready to rock!.
        /// </summary>
        public static string StartJourneyExplanation {
            get {
                return ResourceManager.GetString("StartJourneyExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stats.
        /// </summary>
        public static string Stats {
            get {
                return ResourceManager.GetString("Stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stunt.
        /// </summary>
        public static string Stunt {
            get {
                return ResourceManager.GetString("Stunt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stunt Activity.
        /// </summary>
        public static string StuntActivity {
            get {
                return ResourceManager.GetString("StuntActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stunt List.
        /// </summary>
        public static string StuntList {
            get {
                return ResourceManager.GetString("StuntList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stunts.
        /// </summary>
        public static string Stunts {
            get {
                return ResourceManager.GetString("Stunts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string Team {
            get {
                return ResourceManager.GetString("Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team notes.
        /// </summary>
        public static string Team_notes {
            get {
                return ResourceManager.GetString("Team_notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams.
        /// </summary>
        public static string Teams {
            get {
                return ResourceManager.GetString("Teams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams scoreboard.
        /// </summary>
        public static string TeamsScoreboard {
            get {
                return ResourceManager.GetString("TeamsScoreboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your {0} members have amassed a total of {1} points in {2} stunts..
        /// </summary>
        public static string TeamStatus {
            get {
                return ResourceManager.GetString("TeamStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token.
        /// </summary>
        public static string Token {
            get {
                return ResourceManager.GetString("Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translations.
        /// </summary>
        public static string Translations {
            get {
                return ResourceManager.GetString("Translations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tries.
        /// </summary>
        public static string Tries {
            get {
                return ResourceManager.GetString("Tries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re logged in as.
        /// </summary>
        public static string YourAreLoggedInAs {
            get {
                return ResourceManager.GetString("YourAreLoggedInAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You also have {0} bonus points.
        /// </summary>
        public static string YourBonusPoints {
            get {
                return ResourceManager.GetString("YourBonusPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your secret token is.
        /// </summary>
        public static string YourTokenIs {
            get {
                return ResourceManager.GetString("YourTokenIs", resourceCulture);
            }
        }
    }
}
